kind: Quota
apiVersion: api.ibm.com/v1
metadata:
  name: task-management-mcp-oauth-quota-s6hqi
  namespace: task-management-mcp-oauth
  version: "1.0"
  tags: []
  domain: mcp
spec:
  maxRequest: 1000
  interval: 1m
  extensions:
    dp-nano-gateway:
      apiVersion: api.ibm.com/v1
      spec:
        exceedAction: return429
