kind: Telemetry
apiVersion: api.ibm.com/v1
metadata:
  name: telemetry-s6hqi
  namespace: task-management-mcp-oauth
  version: "1.0"
  tags: []
  domain: mcp
  labels:
    gatewayTypes:
      - nano
spec: {}
