kind: MCPServer
apiVersion: api.ibm.com/v1
metadata:
  name: task-management-api-server-3k0il
  namespace: task-management-mcp
  version: "1.0"
  tags: []
  domain: mcp
  labels:
    origin: mcp-rest
spec:
  title: Task Management API MCP Server
  protocolVersion: V2025_11_25
  quota:
    $ref: task-management-mcp:task-management-mcp-quota-3k0il:1.0
  policy-sequence:
    - $ref: task-management-mcp:task-management-mcp-freeflowpolicysequence-3k0il:1.0
  capabilities:
    tools:
      - $ref: task-management-mcp:task-management-api-tool-3k0il:1.0
